#!/bin/bash

if [ ${UID} -ne 0 ]
then
echo	
echo " You need root access"
echo
exit 0
fi

## Checking number of processors

if [ `nproc` -eq 1 ]
then
echo	
echo" This server is very small"
echo
exit 2
fi
